# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stuPanelLogged_python.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(588, 366)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.comboBox_interests = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_interests.setObjectName("comboBox_interests")
        self.gridLayout.addWidget(self.comboBox_interests, 1, 1, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 1, 1, 1)
        self.comboBox_academics = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_academics.setObjectName("comboBox_academics")
        self.gridLayout.addWidget(self.comboBox_academics, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 588, 22))
        self.menubar.setObjectName("menubar")
        self.menuDosya = QtWidgets.QMenu(self.menubar)
        self.menuDosya.setObjectName("menuDosya")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_uploadTranscript = QtWidgets.QAction(MainWindow)
        self.action_uploadTranscript.setObjectName("action_uploadTranscript")
        self.action_enterTranscript = QtWidgets.QAction(MainWindow)
        self.action_enterTranscript.setObjectName("action_enterTranscript")
        self.action_transcriptView = QtWidgets.QAction(MainWindow)
        self.action_transcriptView.setObjectName("action_transcriptView")
        self.menuDosya.addAction(self.action_uploadTranscript)
        self.menuDosya.addAction(self.action_enterTranscript)
        self.menuDosya.addAction(self.action_transcriptView)
        self.menubar.addAction(self.menuDosya.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "İlgi Alanı"))
        self.label_4.setText(_translate("MainWindow", "Mesajınız"))
        self.label_3.setText(_translate("MainWindow", "Öğretmen"))
        self.pushButton.setText(_translate("MainWindow", "Gönder"))
        self.menuDosya.setTitle(_translate("MainWindow", "Dosya"))
        self.action_uploadTranscript.setText(_translate("MainWindow", "Transkript Yükle"))
        self.action_enterTranscript.setText(_translate("MainWindow", "Transkript Girişi"))
        self.action_transcriptView.setText(_translate("MainWindow", "Transkript Görüntüle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
